[package]
name = "h5sh"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

homepage = "https://github.com/jl-wynen/h5sh"
repository = "https://github.com/jl-wynen/h5sh"
authors = ["Jan-Lukas Wynen"]
license = "MIT"
description = "Interactive shell for HDF5 files"

[dependencies]
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.29"
dirs = "6.0"
hdf5 = { package = "hdf5-metno", version = "0.10", features = ["static"] }
indexmap = "2.9"
log = "0.4"
lscolors = { version = "0.20" }
nu-ansi-term = "0.50"
rustyline = { version = "16", default-features = false, features = ["with-file-history"] }
smallvec = { version = "2.0.0-alpha.11", features = ["std"] }
uutils_term_grid = "0.7"

[dev-dependencies]
pretty_assertions = "1.4.1"

[profile.release]
lto = 'thin'
codegen-units = 1
strip = true
