# Use a custom CentOS image.
# The image needs to use a custom CMake installation because HDF5 cannot be compiled
# with the default on CentOS 7.
[target.x86_64-unknown-linux-gnu.dockerfile]
file = "./Dockerfile-cross-centos"
context = "."
build-args = { CMAKE_VERSION = "3.29.8" }
