name: CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Formatting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.13.0
        with:
          components: rustfmt
      - name: Test | Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1.1.1

  clippy:
    name: Clippy
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.13.0
        with:
          components: clippy
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Cargo clippy
        run: cargo clippy -- -Dwarnings

  test:
    name: Test (${{ matrix.target }})
    needs: [ format, clippy ]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
           - target: x86_64-unknown-linux-gnu
             os: ubuntu-24.04
           - target: centos-7
             os: ubuntu-24.04
           - target: aarch64-apple-darwin
             os: macos-15
           - target: x86_64-pc-windows-msvc
             os: windows-2025
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Install mold
        uses: rui314/setup-mold@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.13.0
      - name: Install cross [Linux]
        if: "matrix.target == 'centos-7'"
        uses: taiki-e/install-action@cross
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build [Cargo]
        if: "matrix.target != 'centos-7'"
        run: cargo build --verbose --target "${{ matrix.target }}"
      - name: Build [Cross]
        if: "matrix.target == 'centos-7'"
        # Using the x86_64-unknown-linux-gnu with cross triggers a CentOS-7 build.
        run: cross build --verbose --target "x86_64-unknown-linux-gnu"
      - name: Run tests [Cargo]
        if: "matrix.target != 'centos-7'"
        run: cargo test --verbose --target "${{ matrix.target }}"
      - name: Run tests [Cross]
        if: "matrix.target == 'centos-7'"
        run: cross test --verbose --target "x86_64-unknown-linux-gnu"
